# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedAt', models.DateField(auto_created=True)),
                ('createdAt', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('is_blocked', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedAt', models.DateField(auto_created=True)),
                ('createdAt', models.DateField(auto_created=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SubCategory'),
        ),
    ]
