# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 17:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='bank_ac_name',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bank_ac_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bank_name',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_partners',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Courier'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='mm_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Wrong phone number format', regex='^(256|254|255|0)[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
