# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='subCategory',
        ),
    ]
