# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170731_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Category'),
            preserve_default=False,
        ),
    ]
