# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20170801_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modifiedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
