# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_order_modifiedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Courier'),
            preserve_default=False,
        ),
    ]
