# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='courier',
        ),
        migrations.AddField(
            model_name='driver',
            name='courier',
            field=models.ManyToManyField(to='myapp.Courier'),
        ),
    ]
