# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20170807_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Courier')),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='courier',
        ),
        migrations.AddField(
            model_name='courierdrivers',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver'),
        ),
    ]
