# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='element',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='parameter',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
