# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20170816_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='element',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='parameter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
