# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20170816_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('number_plate', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='couriervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Vehicle'),
        ),
    ]
