# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20170817_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='activate',
            new_name='activated',
        ),
    ]
