# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_productbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Brand'),
        ),
    ]
