# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_shopsubscription_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsubscription',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopsubscription',
            name='subscription',
        ),
        migrations.AddField(
            model_name='shop',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Subscription'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShopSubscription',
        ),
    ]
