# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(max_length=254, upload_to='profile/'),
        ),
    ]
