# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_auto_20170818_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPhoto',
        ),
    ]
