# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_delete_myphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=1, max_length=254, upload_to='brand/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(default=1, max_length=254, upload_to='subscription/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=1, max_length=254, upload_to='vehicle/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=254, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=254, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(max_length=254, upload_to='sub_category/'),
        ),
    ]
