# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-20 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_auto_20170820_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
