# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-20 01:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_auto_20170820_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Wrong phone number format', regex='^/256([a-zA-Z])+/$')]),
        ),
    ]
