# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_auto_20170820_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopreview',
            name='shop',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.Shop'),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
