# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
