# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_productlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLike',
            new_name='WishList',
        ),
    ]
