# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_auto_20170829_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='count',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='count',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
