# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-18 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_auto_20170907_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=2, help_text='0 - Male, 1 - Female, 2 - Not Specified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=254, upload_to='profile/'),
        ),
    ]
